#!/usr/bin/env bash

input_file="source.md"
template_file="template.tex"
output_file="output.pdf"

#
# Display script usage
#
function show_usage() {
    echo "Build script for converting markdown to PDF using LaTeX."
    echo "Usage:"
    echo "  $(basename $0) [option ...]"
    echo "Options:"
    echo "  -h         print help and exit"
    echo "  -i <file>  specific git tag"
    echo "  -t <file>  update all project git repositories"
    echo "  -o <file>  build the currently checked out version of all git repositories"
}

# ==============================

if [ $# -eq 0 ]; then
    return
fi

if [ "$1" = "--help" ]; then
    show_usage
    exit
fi

while getopts :hi:t:o: OPTION; do
    case $OPTION in
        h)      show_usage
                exit
                ;;
        i)      input_file="$OPTARG"
                ;;
        t)      template_file="$OPTARG"
                ;;
        o)      output_file="$OPTARG"
                ;;
        \:)     printf "argument missing from -%s option\n" $OPTARG
                show_usage
                exit 2
                ;;
        \?)     show_usage
                exit 2
                ;;
    #esac >&2
    esac
done
shift $(($OPTIND - 1))

echo "Build arguments:"
echo "  Input:    $input_file"
echo "  Template: $template_file"
echo "  Output:   $output_file"

if [ $# -gt 0 ]; then
    printf "Unknown arguments: %s\n" "$*"
    echo   "Aborting."
    exit
fi

pandoc  ${input_file}                   \
        --template=${template_file}     \
        -f markdown+raw_tex+fenced_code_blocks+footnotes   \
        -t latex                        \
        -o ${output_file}               \
        --pdf-engine=pdflatex           \
        --toc                           \
        --top-level-division=chapter

echo "Done."
